<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->insert([
            // Tops
            // Tops
            [
                'ca_variable_id' => 1,
                'ca_variable_value' => 'tops',
                'ca_id' => 1,
                'ca_tops_value' => 'Tシャツ',
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 1,
                'ca_variable_value' => 'tops',
                'ca_id' => 2,
                'ca_tops_value' => 'シャツ',
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 1,
                'ca_variable_value' => 'tops',
                'ca_id' => 3,
                'ca_tops_value' => 'ブラウス',
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 1,
                'ca_variable_value' => 'tops',
                'ca_id' => 4,
                'ca_tops_value' => 'ポロシャツ',
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 1,
                'ca_variable_value' => 'tops',
                'ca_id' => 5,
                'ca_tops_value' => 'タンクトップ',
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 1,
                'ca_variable_value' => 'tops',
                'ca_id' => 6,
                'ca_tops_value' => 'スウェットシャツ',
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 1,
                'ca_variable_value' => 'tops',
                'ca_id' => 7,
                'ca_tops_value' => 'カーディガン',
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 1,
                'ca_variable_value' => 'tops',
                'ca_id' => 8,
                'ca_tops_value' => 'パーカー',
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],


            // Botms
            
            [
                'ca_variable_id' => 2,
                'ca_variable_value' => 'botms',
                'ca_id' => 1,
                'ca_tops_value' => null,
                'ca_botms_value' => 'ジーンズ',
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 2,
                'ca_variable_value' => 'botms',
                'ca_id' => 2,
                'ca_tops_value' => null,
                'ca_botms_value' => 'スラックス',
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 2,
                'ca_variable_value' => 'botms',
                'ca_id' => 3,
                'ca_tops_value' => null,
                'ca_botms_value' => 'ショートパンツ',
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 2,
                'ca_variable_value' => 'botms',
                'ca_id' => 4,
                'ca_tops_value' => null,
                'ca_botms_value' => 'スカート',
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 2,
                'ca_variable_value' => 'botms',
                'ca_id' => 5,
                'ca_tops_value' => null,
                'ca_botms_value' => 'レギンス',
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 2,
                'ca_variable_value' => 'botms',
                'ca_id' => 6,
                'ca_tops_value' => null,
                'ca_botms_value' => 'パンツ',
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 2,
                'ca_variable_value' => 'botms',
                'ca_id' => 7,
                'ca_tops_value' => null,
                'ca_botms_value' => 'ショーツ',
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 2,
                'ca_variable_value' => 'botms',
                'ca_id' => 8,
                'ca_tops_value' => null,
                'ca_botms_value' => 'キュロット',
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            // Dores
            [
                'ca_variable_id' => 3,
                'ca_variable_value' => 'dores',
                'ca_id' => 1,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => 'カジュアルドレス',
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 3,
                'ca_variable_value' => 'dores',
                'ca_id' => 2,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => 'カクテルドレス',
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 3,
                'ca_variable_value' => 'dores',
                'ca_id' => 3,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => 'イブニングドレス',
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 3,
                'ca_variable_value' => 'dores',
                'ca_id' => 4,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => '結婚式のドレス',
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 3,
                'ca_variable_value' => 'dores',
                'ca_id' => 5,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => 'マキシドレス',
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 3,
                'ca_variable_value' => 'dores',
                'ca_id' => 6,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => 'ミディドレス',
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 3,
                'ca_variable_value' => 'dores',
                'ca_id' => 7,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => 'ミニドレス',
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 3,
                'ca_variable_value' => 'dores',
                'ca_id' => 8,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => 'サマードレス',
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],

            // 他のカテゴリーアイテムに関するデータも同様に挿入

            // Outerware
            [
                'ca_variable_id' => 4,
                'ca_variable_value' => 'outerware',
                'ca_id' => 1,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => 'ジャケット',
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 4,
                'ca_variable_value' => 'outerware',
                'ca_id' => 2,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => 'コート',
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 4,
                'ca_variable_value' => 'outerware',
                'ca_id' => 3,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => 'ブルゾン',
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 4,
                'ca_variable_value' => 'outerware',
                'ca_id' => 4,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => 'ベスト',
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 4,
                'ca_variable_value' => 'outerware',
                'ca_id' => 5,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => 'ピーコート',
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 4,
                'ca_variable_value' => 'outerware',
                'ca_id' => 6,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => 'ダウンジャケット',
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 4,
                'ca_variable_value' => 'outerware',
                'ca_id' => 7,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => 'ブレザー',
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 4,
                'ca_variable_value' => 'outerware',
                'ca_id' => 8,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => 'カーディガン',
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],


            // 他のカテゴリーアイテムに関するデータも同様に挿入

            // Innerware
            
            // Innerware
            [
                'ca_variable_id' => 5,
                'ca_variable_value' => 'innerware',
                'ca_id' => 1,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => 'ブラジャー',
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 5,
                'ca_variable_value' => 'innerware',
                'ca_id' => 2,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => 'パンティー',
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 5,
                'ca_variable_value' => 'innerware',
                'ca_id' => 3,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => 'ショーツ',
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 5,
                'ca_variable_value' => 'innerware',
                'ca_id' => 4,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => 'キャミソール',
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 5,
                'ca_variable_value' => 'innerware',
                'ca_id' => 5,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => 'スリップ',
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 5,
                'ca_variable_value' => 'innerware',
                'ca_id' => 6,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => 'タンクトップ',
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 5,
                'ca_variable_value' => 'innerware',
                'ca_id' => 7,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => 'ボクサーショーツ',
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 5,
                'ca_variable_value' => 'innerware',
                'ca_id' => 8,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => 'レディースタンゴ',
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],


            
            // Accessory
            [
                'ca_variable_id' => 6,
                'ca_variable_value' => 'accessory',
                'ca_id' => 1,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => 'ネックレス',
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 6,
                'ca_variable_value' => 'accessory',
                'ca_id' => 2,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => 'ブレスレット',
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 6,
                'ca_variable_value' => 'accessory',
                'ca_id' => 3,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => 'イヤリング',
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 6,
                'ca_variable_value' => 'accessory',
                'ca_id' => 4,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => 'リング',
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 6,
                'ca_variable_value' => 'accessory',
                'ca_id' => 5,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => 'バッグ',
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 6,
                'ca_variable_value' => 'accessory',
                'ca_id' => 6,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => '帽子',
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 6,
                'ca_variable_value' => 'accessory',
                'ca_id' => 7,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => 'サングラス',
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 6,
                'ca_variable_value' => 'accessory',
                'ca_id' => 8,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => 'スカーフ',
                'ca_shoes_value' => null,
                'ca_overlap_value' => null,
            ],

            // Shoes
            // Shoes
            [
                'ca_variable_id' => 7,
                'ca_variable_value' => 'shoes',
                'ca_id' => 1,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => 'スニーカー',
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 7,
                'ca_variable_value' => 'shoes',
                'ca_id' => 2,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => 'ブーツ',
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 7,
                'ca_variable_value' => 'shoes',
                'ca_id' => 3,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => 'ヒールシューズ',
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 7,
                'ca_variable_value' => 'shoes',
                'ca_id' => 4,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => 'フラットシューズ',
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 7,
                'ca_variable_value' => 'shoes',
                'ca_id' => 5,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => 'サンダル',
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 7,
                'ca_variable_value' => 'shoes',
                'ca_id' => 6,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => 'ローファー',
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 7,
                'ca_variable_value' => 'shoes',
                'ca_id' => 7,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => 'エスパドリーユ',
                'ca_overlap_value' => null,
            ],
            [
                'ca_variable_id' => 7,
                'ca_variable_value' => 'shoes',
                'ca_id' => 8,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => 'レインブーツ',
                'ca_overlap_value' => null,
            ],

            // Overlap
            // Overlap
            [
                'ca_variable_id' => 8,
                'ca_variable_value' => 'overlap',
                'ca_id' => 1,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => '帽子',
            ],
            [
                'ca_variable_id' => 8,
                'ca_variable_value' => 'overlap',
                'ca_id' => 2,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => 'ビーニー',
            ],
            [
                'ca_variable_id' => 8,
                'ca_variable_value' => 'overlap',
                'ca_id' => 3,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => 'ハット',
            ],
            [
                'ca_variable_id' => 8,
                'ca_variable_value' => 'overlap',
                'ca_id' => 4,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => 'キャップ',
            ],
            [
                'ca_variable_id' => 8,
                'ca_variable_value' => 'overlap',
                'ca_id' => 5,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => 'フード',
            ],
            [
                'ca_variable_id' => 8,
                'ca_variable_value' => 'overlap',
                'ca_id' => 6,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => 'ヘッドバンド',
            ],
            [
                'ca_variable_id' => 8,
                'ca_variable_value' => 'overlap',
                'ca_id' => 7,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => 'ターバン',
            ],
            [
                'ca_variable_id' => 8,
                'ca_variable_value' => 'overlap',
                'ca_id' => 8,
                'ca_tops_value' => null,
                'ca_botms_value' => null,
                'ca_dores_value' => null,
                'ca_outerware_value' => null,
                'ca_innerware_value' => null,
                'ca_accessory_value' => null,
                'ca_shoes_value' => null,
                'ca_overlap_value' => 'ヘッドピース',
            ],
        ]);
    }
}
